Adapt Moodle's push.yml workflow into moodle-ci.yml

diff --git a/.github/workflows/moodle-ci.yml b/.github/workflows/moodle-ci.yml
--- a/.github/workflows/moodle-ci.yml
+++ b/.github/workflows/moodle-ci.yml
@@ -103,9 +103,9 @@ jobs:
         if: ${{ !cancelled() }}
         run: moodle-plugin-ci validate
 
-      - name: Check upgrade savepoints
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci savepoints
+      # - name: Check upgrade savepoints
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci savepoints
 
       - name: Mustache Lint
         if: ${{ !cancelled() }}
@@ -119,15 +119,15 @@ jobs:
         if: ${{ !cancelled() }}
         run: moodle-plugin-ci phpunit --fail-on-warning
 
-      - name: Initialise PHPUnit
-        working-directory: ./moodle
-        run: |
-          php public/admin/tool/phpunit/cli/init.php --no-composer-self-update
+      # - name: Initialise PHPUnit
+      #   working-directory: ./moodle
+      #   run: |
+      #     php public/admin/tool/phpunit/cli/init.php --no-composer-self-update
 
-      - name: Run PHPUnit tests against Moodle core
-        working-directory: ./moodle
-        run: |
-          vendor/bin/phpunit --fail-on-warning
+      # - name: Run PHPUnit tests against Moodle core
+      #   working-directory: ./moodle
+      #   run: |
+      #     vendor/bin/phpunit --fail-on-warning
 
       - name: Behat features
         id: behat
@@ -146,3 +146,241 @@ jobs:
       - name: Mark cancelled jobs as failed.
         if: ${{ cancelled() }}
         run: exit 1
+
+  # Adapted from https://github.com/moodle/moodle/blob/MOODLE_502_STABLE/.github/workflows/push.yml
+  # Updated to run with these plugins installed.
+  # PHPUnit:
+  #   runs-on: ubuntu-24.04
+
+  #   services:
+  #     exttests:
+  #       image: moodlehq/moodle-exttests
+  #       ports:
+  #         - 8080:80
+
+  #     postgres:
+  #       image: ${{ matrix.database == 'pgsql' && 'postgres:17' || '' }}
+  #       env:
+  #         POSTGRES_USER: 'postgres'
+  #         POSTGRES_HOST_AUTH_METHOD: 'trust'
+  #       ports:
+  #         - 5432:5432
+  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
+
+  #     mariadb:
+  #       image: ${{ matrix.database == 'mariadb' && 'mariadb:11' || '' }}
+  #       env:
+  #         MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: '1'
+  #         MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
+  #         MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
+  #       ports:
+  #         - 3306:3306
+  #       options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval 10s --health-timeout 5s --health-retries 3
+
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       php: ['8.3', '8.4']
+  #       moodle-branch: ['MOODLE_501_STABLE']
+  #       database: [pgsql, mariadb]
+
+  #   steps:
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v6
+  #       with:
+  #         path: plugin
+  #         persist-credentials: false
+
+  #     - name: Setup PHP ${{ matrix.php }}
+  #       uses: shivammathur/setup-php@v2
+  #       with:
+  #         php-version: ${{ matrix.php }}
+  #         ini-values: max_input_vars=5000, opcache.enable_cli=1
+  #         coverage: none
+
+  #     - name: Initialise moodle-plugin-ci
+  #       run: |
+  #         composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
+  #         echo $(cd ci/bin; pwd) >> $GITHUB_PATH
+  #         echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
+
+  #     - name: Install Moodle
+  #       run: moodle-plugin-ci install --plugin ./plugin/public/local/kaltura --db-host=127.0.0.1
+  #       env:
+  #         DB: ${{ matrix.database }}
+  #         MOODLE_BRANCH: ${{ matrix.moodle-branch }}
+
+  #     - name: Initialise PHPUnit
+  #       working-directory: ./moodle
+  #       run: |
+  #         sudo locale-gen en_AU.UTF-8
+  #         php public/admin/tool/phpunit/cli/init.php --no-composer-self-update
+
+  #     - name: Run PHPUnit tests against Moodle core
+  #       working-directory: ./moodle
+  #       run: |
+  #         vendor/bin/phpunit --fail-on-warning
+
+  #     - name: Mark cancelled jobs as failed.
+  #       if: ${{ cancelled() }}
+  #       run: exit 1
+
+# name: PHPUnit
+
+# on:
+#   push:
+#   pull_request:
+#   workflow_dispatch:
+#     inputs:
+#       moodle_ref:
+#         description: Moodle branch or tag to test against
+#         required: true
+#         default: MOODLE_502_STABLE
+
+#       phpunit_extra_options:
+#         description: Additional options to apply to PHPUnit
+#         required: false
+#         default: ''
+
+# env:
+#   MOODLE_REPOSITORY: https://github.com/moodle/moodle.git
+#   MOODLE_REF: ${{ inputs.moodle_ref || 'MOODLE_502_STABLE' }}
+
+# jobs:
+  PHPUnit:
+    runs-on: ${{ matrix.os }}
+    services:
+      exttests:
+        image: moodlehq/moodle-exttests
+        ports:
+          - 8080:80
+      redis:
+        image: redis
+        ports:
+          - 6379:6379
+      postgres:
+        image: ${{ matrix.db == 'pgsql' && 'postgres:16' || '' }}
+        env:
+          POSTGRES_DB: test
+          POSTGRES_USER: test
+          POSTGRES_PASSWORD: test
+        ports:
+          - 5432:5432
+    strategy:
+      fail-fast: false
+      matrix:
+        moodle-branch: ['MOODLE_501_STABLE']
+        include:
+          # MySQL builds always run with the lowest PHP supported version.
+          - os: ubuntu-24.04
+            php: 8.3
+            extensions:
+            db: mysqli
+          # PostgreSQL builds always run with the highest PHP supported version.
+          - os: ubuntu-24.04
+            php: 8.4
+            db: pgsql
+
+    steps:
+
+      #
+      # 4. Start MySQL only for the MySQL matrix entry.
+      #
+      - name: Run MySQL Server
+        if: ${{ matrix.db == 'mysqli' }}
+        run: |
+          docker run --rm \
+            -e MYSQL_DATABASE=test \
+            -e MYSQL_USER=test \
+            -e MYSQL_PASSWORD=test \
+            -e MYSQL_ROOT_PASSWORD=test \
+            -p 3306:3306 \
+            -d \
+            --tmpfs /var/lib/mysql:rw,noexec,nosuid,size=1024M \
+            mysql:8.4 \
+              --skip-log-bin \
+              --collation-server=utf8mb4_bin
+
+      #
+      # 6. Configure Git variables.
+      #
+      - name: Configuring git vars
+        uses: rlespinasse/github-slug-action@v4
+
+      #
+      # 5. Configure PHP.
+      #
+      - name: Setting up PHP ${{ matrix.php }}
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: ${{ matrix.php }}
+          extensions: ${{ matrix.extensions }}
+          ini-values: max_input_vars=5000
+          coverage: none
+
+      #
+      # 1. Check out YOUR plugin repository.
+      #
+      # - name: Checking out plugins
+      #   uses: actions/checkout@v4
+      #   with:
+      #     path: plugin
+      - name: Check out repository code
+        uses: actions/checkout@v6
+        with:
+          path: plugin
+          persist-credentials: false
+
+      #
+      # 2. Check out Moodle core separately.
+      #
+      - name: Checking out Moodle ${{ matrix.moodle-branch }}
+        uses: actions/checkout@v4
+        # uses: actions/checkout@v6
+        with:
+          repository: moodle/moodle
+          ref: ${{ matrix.moodle-branch }}
+          path: moodle
+
+      # #
+      # # 3. Put the plugin into the Moodle checkout.
+      # #
+      # # Change MOD_PLUGIN_NAME to your plugin's directory name.
+      # #
+      # - name: Installing plugin
+      #   run: |
+      #     mkdir -p moodle/mod/MOD_PLUGIN_NAME
+      #     cp -a plugin/. moodle/mod/MOD_PLUGIN_NAME/
+
+      #
+      # 7. Configure Moodle.
+      #
+      - name: Setting up PHPUnit in Moodle
+        working-directory: moodle
+        env:
+          dbtype: ${{ matrix.db }}
+        run: |
+          echo "pathtophp=$(which php)" >> $GITHUB_ENV # Inject installed pathtophp to env. The template config needs it.
+          cp .github/workflows/config-template.php config.php
+          mkdir -p ../moodledata
+          sudo locale-gen en_AU.UTF-8
+
+          php public/admin/tool/phpunit/cli/init.php \
+            --no-composer-self-update
+
+      #
+      # 8. Run the plugin's PHPUnit tests.
+      #
+      - name: Running PHPUnit tests
+        working-directory: moodle
+        env:
+          dbtype: ${{ matrix.db }}
+          phpunit_options: ${{ secrets.phpunit_options }}
+        run: vendor/bin/phpunit $phpunit_options ${{ inputs.phpunit_extra_options }}
+
+      #
+      # 9. Show status for debugging.
+      #
+      - name: Git status
+        working-directory: plugin
+        run: git status --short
